apps/pushy/src/pushy_principal.erl, apps/pushy/test/pushy_principal_test.erl
This splits out the tests as mentioned in #111
=> Add tests for pushy_principal:fetch_principal/2

omnibus/config/projects/opscode-push-jobs-server.rb
=> [omnibus] Use latest chef and ruby from omnibus-software

omnibus/config/software/opscode-pushy-server-ctl.rb, omnibus/config/software/pushy-server-cookbooks.rb, omnibus/config/software/pushy-server-scripts.rb
=> [omnibus] Use :project_license for local projects

oc-pushy-pedant/spec/pushy/integration/end_to_end_spec.rb, oc-pushy-pedant/spec/pushy/integration/sse_spec.rb, oc-pushy-pedant/spec/pushy/spec_helper.rb, oc-pushy-pedant/spec/pushy/support/end_to_end_util.rb, oc-pushy-pedant/spec/pushy/support/key_cache.rb, oc-pushy-pedant/spec/pushy/support/sse_util.rb
- Cache chef client keys between tests
- Use a Logger class for test output rather than `puts` and `pp`
- Add more diagnostic log messages throughout the test suite
=> Test suite improvements

.gitignore, Dockerfile, Makefile, README.md
Adds a `make shell` target that will start a Docker container with the
goods. Also some minor readme updates.
=> Docker dev environment

omnibus/config/software/pushy-server-schema.rb
=> Use path source for pushy-server-schema in omnibus

rebar.lock
=> Update pushy_common dep

omnibus/config/software/oc-pushy-pedant.rb, omnibus/files/pushy-server-cookbooks/opscode-pushy-server/recipes/bootstrap.rb
Remove it from the omnibus software and remove a comment that even dares
to mention its name.
Also remove an unused variable from that recipe.
=> Remove dependency on curl

RELEASE_PROCESS.md
ok so this was copied from the chef server's version of this. I left all the testing stuff there, so:
[ ] what should go in the testing part?
[ ] is the rest of the doc sufficient for release instructions?
=> [WIP] add release process doc

oc-pushy-pedant/Gemfile, oc-pushy-pedant/Gemfile.lock, omnibus/files/pushy-server-ctl-commands/test.rb
=> oc-chef-pedant no longer requires veil directly

omnibus/files/pushy-server-ctl-commands/test.rb
=> Don't enable webui tests

CHANGELOG.md, RELEASE_NOTES.md
Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>
=> Release notes and changelog

omnibus/config/projects/opscode-push-jobs-server.rb
The format for RPM and DEB is slightly different, but this works.
Signed-off-by: Stephan Renatus <srenatus@chef.io>
=> Depend on chef-server >= 12.14.0

CHANGELOG.md, RELEASE_NOTES.md
=> Update CHANGELOG and RELEASE_NOTES for 2.2.1

CHANGELOG.md, RELEASE_NOTES.md, RELEASE_PROCESS.md
I was a bit optimistic with _today_, but maybe we can get this over with? 😃
=> Release 2.2.2

RELEASE_PROCESS.md
I've forgotten that in my earlier update 🙄
=> RELEASE_PROCESS-=chef-web-downloads (now done automatically on promotion)

.expeditor/config.yml
Signed-off-by: Tom Duffield <tom@chef.io>
=> Update the CHANGELOG when push-server is promoted to stable

.expeditor/config.yml, CHANGELOG.md
Signed-off-by: Tom Duffield <tom@chef.io>
=> Update Expeditor config to meet 0.5.0 requirements

oc-pushy-pedant/Gemfile.lock, omnibus/Gemfile.lock, omnibus_overrides.rb
http://wilson.cd.chef.co/job/push-jobs-server-trigger-ad_hoc/5/downstreambuildview/
=> Update to ruby 2.4.3

apps/pushy/include/pushy_wm.hrl, apps/pushy/src/pushy_config_resource.erl
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
=> MSYS-832 : Added Max_body_size configurable

.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md, .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
Use github's new selectable issue template feature
Adapted from chef/chef#7859
Signed-off-by: Mark Anderson <mark@chef.io>
=> Add github issue templates

.expeditor/config.yml
The previous config was throwing deprecation warnings
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Update expeditor config

omnibus/omnibus-test.sh
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
=> Fix omnibus-test.sh to use correct product name

.expeditor/config.yml
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
=> Replace Jenkins omnibus build/test pipeline with Buildkite

.expeditor/config.yml, .expeditor/verify.pipeline.yml, pushy-server-schema/Makefile, scripts/bk_tests/bk_install.sh, scripts/bk_tests/pb_hba.conf
Signed-off-by: Jaymala Sinha <jsinha@chef.io>
Add Buildkite verify pipeline
[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]
=> Migrate verification tests to Buildkite
